# Generated by Django 5.1.3 on 2024-11-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acount',
        ),
    ]
