# Generated by Django 5.1.3 on 2025-04-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'حساب کاربری', 'verbose_name_plural': 'حساب کاربری ها'},
        ),
    ]
